import { Colors } from '../../Lib/Themes';
export const styles = {
  newText: {
    flex: 1,
    color: Colors.white,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
  },
  letterContainer: {
    flex: '1',
    display: 'flex',
    flexDirection: 'column',
  },
  secondText: {
    flex: 1,
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
  },
  container: {
    flex: '1',
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  audioContainer: {
    flex: '1',
    cursor: 'pointer',
    justifyContent: 'center',
    display: 'flex',
    alignItems: 'center',
  },
  letterFont: {
    flex: 1,
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
  },
  baseUnitHeader: {
    height: 57,
    backgroundColor: 'white',
    fontSize: 20,
    color: '#00a65a',
    display: 'flex',
    justifyContent: 'center',
    borderLeft: '3px solid red',
    borderRight: '3px solid #00a65a',
    margin: 0,
    alignItems: 'center',
  },
};
